server:
  port: ${SERVER_PORT}

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  dbname: ${DATABASE_DBNAME}
  sslmode: ${DATABASE_SSLMODE}
